### ISSUE TITLE
Question: How to get the db from `const db = getFirestore(app);`

### ISSUE THREAD

**Issue by mxswat** [ensite-in/next-firebase-auth-edge#11]
First of all, sorry if this is a stupid question, but I'm new to firestore and very new to nextjs.13 with `appDir.`

From my understanding of how the auth is implemented inside `firebase-auth.ts` I should be able to access the `db` on both client and server by adding the following to `firebase-auth.ts` 

```ts
// appended to firebase-auth.ts

const getDB = async (options: FirebaseOptions) => {
  const app = await getFirebaseApp(options);
  const { getFirestore } = await import('firebase/firestore')
  
  return getFirestore(app)
}

export const useFirebaseFirestore = (options: FirebaseOptions) => {
  const getFirebaseFirestore = async () => {
    return getDB(options);
  };

  return { getFirebaseFirestore };
};
```

Do you think this is the correct approach? 
Or should I do something different? 

Please let me know, and thank you for this great library!

**Comment by awinogrodzki** [comment]
I'll close the issue for now. If you'll have some further questions please feel free to mention me in a comment below and I'd be happy to answer

**Comment by mxswat** [comment]
Hello, @awinogrodzki. Thank you for the answer. 

I took some time to reflect on the information you gave me, and I realized that middleware is quite an advanced feature for someone new to nextJS. And makes me question if I need to use middleware. And I also realized that I have no idea how `firebase-admin` works and why it is useful, and I will look into it.

And to explain my use case, I should provide more context of what I am trying to achieve with my first nextJS13 project.

A simple web app for Todos. And It consists of the following pages.

* Todo Editor `app/todo/editor/[todoId]`
* All Todos `app/todo/[todoId]`
* List of Todos `app/todos/` 
* Admin `app/admin.`

My idea is each user has their list of todos, and they can see and edit their todos but only edit the todo they own.

And when a user visits  `app/todo/[todoId],` I want to use the new _Server Components_ to pre-render the page and have a stored, cached version so the user can check his TODO without any delay. 
And this is why I need to use `firestore` on the backend. 
And the same logic of using Server Components would be applied to the All Todos `app/todo/[todoId], too, with SSR and cache`.

The Todo Editor `app/todo/editor/[todoId]` is nothing special, and all Client Components.

And ultimately, the `Admin `app/admin.` and ` Todo Editor `app/todo/editor/[todoId]` need to have some way to stop unauthorized and not logged-in users from visualizing the page and instead being redirected to the login page.

Writing all this also made me think I should make my todo app public so it can be used as a bigger example of dealing with auth and DB in nextJS13 with appdir.

**Comment by mxswat** [comment]
Hello, again @awinogrodzki. 
I want to thank you again for the help you gave me. 
But after discussing with some colleagues, I decided that for the moment, given my lack of experience with NextJS, I have decided to drop the idea of using middleware for the auth.

I'll consider returning to this project once I have more experience, and I'm looking forward to trying this again once v1.0 comes out!

**Comment by andreemic** [comment]
> makes

Hey, thanks for this project! Extremely well-documented and well-written.
Your proposal to use API endpoints which run in NodeJS to access Firestore make sense but I have one open question:

**What's the easiest way to authenticate requests to the API endpoints?**
So to know that a request comes from a particular Firebase user.

Context: I'm storing some role data for my users in their Firestore documents. Ideally, I'd fetch them in middleware but if I decide to serve them through API endpoints I'll need to make sure every user can only get their own document. I've found [this](https://stackoverflow.com/questions/37408684/is-it-still-possible-to-do-server-side-verification-of-tokens-in-firebase-3) but looking at your codebase I feel like there must be an easier solution.

**Comment by awinogrodzki** [comment]
Hey @andreemic. Good question. There is a way to authenticate user in API routes, but up until now it wasn't documented in the readme. I've just added it: https://github.com/awinogrodzki/next-firebase-auth-edge#api-routes

Please take a loot and let me know if you miss something
