### ISSUE TITLE
Question: Using custom jwt over a package like jose

### ISSUE THREAD

**Issue by websiddu** [ensite-in/next-firebase-auth-edge#12]
Hi, I have a small question, 

What is the advantage of writing your own library for JWT parsing instead of using a library like https://www.npmjs.com/package/jose ??

Is that the size we are saving or its a more secure implementation?

**Comment by awinogrodzki** [comment]
Hey @websiddu,

Very good question. Before I came up with this library I've tried all of the most popular libraries that would solve my problem. I've also tried `jose`, but it relies heavily on `Buffer` object that is unavailable in [Edge Runtime](https://nextjs.org/docs/api-reference/edge-runtime). The only existing library that seemed to aim to solve the problem was [https://github.com/ajwild/jwebt](https://github.com/ajwild/jwebt). 

Unfortunately `jwebt` is far from being completed, so I had to work the problem out case by case.

I might be missing some context. If you're aware of a `jwt` library that's specifically designed with `Web Crypto API` in mind, I'd be happy to improve my solution!

**Comment by websiddu** [comment]
Interestingly the example https://github.com/vercel/examples/tree/main/edge-functions/jwt-authentication used joes. I will test it out.

On a different note were you able to find a solution for cold starts for the function, I see at-least 4s  load time on cold start. I tried doing a bunch of optimizations they suggested but still, I'm seeing 2-3s using this package. Any thoughts?

**Comment by awinogrodzki** [comment]
@websiddu the example you provided does indeed work with Edge Runtime, but it's not enough to integrate Firebase Authentication. Firebase authenticates itself using `x.509` certificate that needs to be decoded into a buffer. `jose` provides this file https://github.com/panva/jose/blob/8b9955515f6c81b322fe8603201c204de0bfbec2/src/runtime/node/asn1_sequence_decoder.ts to decode ASN.1 sequence, but it does use `Buffer` and thus it fails. 

Firebase certificate has to be signed using `crypto.subtle` inside the middleware, which basically forces the use of `crypto.subtle` elsewhere.

**Comment by websiddu** [comment]
I see. And are you seeing any cold start delays on Vercel? As I mentioned I see at-least 3-4s using this package.

**Comment by awinogrodzki** [comment]
That's interesting – I haven't experienced any cold start delays myself, but I'll look into this. Could you provide an example of your `middleware.ts` or `Edge API Routes`?

**Comment by websiddu** [comment]
Yeah, this is something that I'm doing. Seems like the loading firebase admin is taking too long, on the getServerSideProps. Thanks for your answers. 

And also another question I have, do you see any problems with setting the idToken as a cookie directly than encrypting it? Is it possible to verify the cookie inside an express js app?

**Comment by awinogrodzki** [comment]
@websiddu, that's a great question. Currently, there's no dedicated `express.js` integration. It'll be added sooner than later. Until then you can take a look at `getTokensFromObject` function from `next-firebase-auth-edge/lib/next/tokens`. You should provide a token/secret key pair in a plain object format:
```json
{
  "YourCookieName": "Encrypted token",
  "YourCookieName.sig": "Token signature"
}
```

Setting idToken directly as a cookie introduces a security risk and should be avoided if possible.

I'll close the issue. If you have any other questions feel free to comment below
