### ISSUE TITLE
[Next 13.1.1] [next.config.js] allowMiddlewareResponseBody is no longer available

### ISSUE THREAD

**Issue by atanaskanchev** [ensite-in/next-firebase-auth-edge#13]
In the latest version of Next, `allowMiddlewareResponseBody` has been removed from `NextConfig > experimental`

Ref: [config-schema](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/config-schema.ts)

**Comment by awinogrodzki** [comment]
Hey @atanaskanchev! Thanks for the heads up. :-) I'll release an update shortly

**Comment by awinogrodzki** [comment]
Hello again @atanaskanchev :-) 

I've just released `next-firebase-auth-edge@0.3.0` which depends on Next.js `^13.1.1`. The `allowMiddlewareResponseBody` flag is no longer present in README or examples.
