### ISSUE TITLE
Expired token not getting refreshed in Firebase Authentication Emulator environment

### ISSUE THREAD

**Issue by seanaguinaga** [ensite-in/next-firebase-auth-edge#14]
Hey there!

Does this automatically get new tokens?

<img width="672" alt="Screenshot 2023-01-05 at 7 00 46 AM" src="https://user-images.githubusercontent.com/15254340/210810604-1a805cb6-13d0-4e92-a95d-26bdc31b020f.png">

I am getting this message:

<img width="1084" alt="Screenshot 2023-01-05 at 6 58 18 AM" src="https://user-images.githubusercontent.com/15254340/210810649-0611541e-8aae-4811-aa26-49484b89c613.png">

If I try to use any of the methods from the lib like these:

<img width="837" alt="Screenshot 2023-01-05 at 7 02 23 AM" src="https://user-images.githubusercontent.com/15254340/210811052-f7c6b32a-91d8-4c5d-a35c-139aa446b780.png">

I get this:
<img width="1024" alt="Screenshot 2023-01-05 at 7 02 28 AM" src="https://user-images.githubusercontent.com/15254340/210811107-efdbabc7-ed4a-45f9-ba81-5ae3a97e941f.png">

I've always struggled with refresh tokens myself so I'm not sure what to try next

**Comment by atanaskanchev** [comment]
Something like would do it
```js
 // force refresh the token every 10 minutes
  useEffect(() => {
    const handle = setInterval(async () => {
      const user = firebaseClient.auth().currentUser;
      if (user) await user.getIdToken(true);
    }, 10 * 60 * 1000);

    // clean up setInterval
    return () => clearInterval(handle);
  }, []);
  ```

**Comment by seanaguinaga** [comment]
This happened when refreshing the page after putting the computer to sleep with localhost/emulators open so it wouldn't have had the chance to do that setInterval()

Would be interested in an isomorphic solution - one that would work on both client and server

**Comment by seanaguinaga** [comment]
Looks like using that force refresh you just suggested @atanaskanchev  in a condition inside of the auth-provider from the examples does the trick?

<img width="1192" alt="Screenshot 2023-01-05 at 10 19 45 AM" src="https://user-images.githubusercontent.com/15254340/210852385-c01aeb03-8a3f-4e28-aaa9-f854cbc0276f.png">

**Comment by seanaguinaga** [comment]
Update:

That doesn't really work - get a jwt issued at future error on first refresh after it expires later

**Comment by awinogrodzki** [comment]
Hey @seanaguinaga! Thanks for the question.

`getTokens` and `getTokensFromObject` functions should refresh expired token automatically.

I have a few questions regarding provided example:

1. What library do you use to decode the token in `src/relay/environment.ts`? Does it work if you decode the token using `decode` function from this library file: https://github.com/ensite-in/next-firebase-auth-edge/blob/9856d979cb14dbd7583e96752baec99120321553/src/auth/jwt/decode.ts ?

2. What is your use case? What do you want to achieve by decoding this token? 
3. `getTokens` resolves with `token` and `decodedToken`. `token`'s primary function is to authorize API requests. `decodedToken` is a decoded version of the token, so there is no need to decode it explicitly. 

Could you log out a token and paste it here? I'll try to test it against a JWT library to figure out the reason you're getting the error. Please only paste a token that's invalid, comes from testing environment and does not contain any vulnerable data :-)

**Comment by seanaguinaga** [comment]
expo-jwt is the library I am using

If I send a token from in memory/from getTokens I want to make sure it is not expired before sending it in the Auth header to my server

the decodeToken from expo-jwt fails if it is expired so I just us that to then tell it to try and get a new updated token as opposed to the request failing

the getTokens() function was never refreshing the expired token when using the emulator from what I saw, so I tried to get that functionality by manually getting a refreshed token with the utils that are in your library, but then those did weird stuff with that kid error

Just trying to make sure that my token is always valid and not expired when using it in my relay fetch-function which could run on server or client.

I can send the expired token when it happens again!

**Comment by seanaguinaga** [comment]
![Screenshot_20230108_030856](https://user-images.githubusercontent.com/15254340/211223728-56dd5e39-9586-41fc-9711-5660e05a7311.png)
![Screenshot_20230108_030956](https://user-images.githubusercontent.com/15254340/211223730-09da773b-3e10-434e-aa4b-89a9c536c577.png)

I also use expo-jwt to allow emulator tokens to be signed/decoding so that custom claims work with hasura - otherwise with alg "none" custom claims on the jwt are ignored so I couldn't test permissions locally

**Comment by awinogrodzki** [comment]
@seanaguinaga 👋 

Here's the PR that should fix the issue. https://github.com/ensite-in/next-firebase-auth-edge/pull/18

I was skipping entire token verification on Firebase Emulator environment, whereas official `firebase-admin` library skips only the signature check. I adjusted the code to work the same.

You can test it by installing `next-firebase-auth-edge@0.2.16-1` :-) Let me know if it works for you

**Comment by seanaguinaga** [comment]
Looks like it is still expired?

eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiU2VhbiBBZ3VpbmFnYSIsInBpY3R1cmUiOiIiLCJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiLCJpbnRlcm5hbCJdLCJ4LWhhc3VyYS11c2VyLWlkIjoiMzc3Zjc3MDUtOTc3Yi00MTUwLTk5MWItNjVlMjE1ZmJkM2E0IiwieC1oYXN1cmEtZmlyZWJhc2UtdWlkIjoidlFIdG9sVVlTVldXbnY1NEN3NEhjenQwV3VSVSJ9LCJlbWFpbCI6InNlYW4uYWd1aW5hZ2FAcm91bmQudGVjaCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjczMzczNzgyLCJ1c2VyX2lkIjoidlFIdG9sVVlTVldXbnY1NEN3NEhjenQwV3VSVSIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic2Vhbi5hZ3VpbmFnYUByb3VuZC50ZWNoIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiY3VzdG9tIn0sImlhdCI6MTY3MzM3Mzc4MiwiZXhwIjoxNjczMzc3MzgyLCJhdWQiOiJyb3VuZC1wb3J0YWwtZGV2IiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3JvdW5kLXBvcnRhbC1kZXYiLCJzdWIiOiJ2UUh0b2xVWVNWV1dudjU0Q3c0SGN6dDBXdVJVIn0.

logged from:

<img width="572" alt="Screenshot 2023-01-10 at 12 17 35 PM" src="https://user-images.githubusercontent.com/15254340/211653252-3973d6bf-cb69-4d5c-8ab2-8c59d545b294.png">

<img width="572" alt="Screenshot 2023-01-10 at 12 16 29 PM" src="https://user-images.githubusercontent.com/15254340/211653392-e1aa5dec-15bc-4c3f-9bae-4874a17055f0.png">

It is 12:18PT now

**Comment by seanaguinaga** [comment]
Wait... Didn't update deps in this repo... standby 🤦‍♂️

**Comment by seanaguinaga** [comment]
Seems to work! But occasionally I am getting this from my endpoint upon refresh:

<img width="976" alt="Screenshot 2023-01-10 at 7 58 08 PM" src="https://user-images.githubusercontent.com/15254340/211714606-e6cf27a3-3415-4f2e-9a68-c77e301e1e6e.png">


issued at future?

**Comment by awinogrodzki** [comment]
@seanaguinaga 

<img width="410" alt="Zrzut ekranu 2023-01-11 o 09 51 18" src="https://user-images.githubusercontent.com/12574743/211761016-49d3bc5c-48ad-4e09-a982-e78293750268.png">

The custom token is setting `iat` (issued at) value correctly. What you are experiencing is a clock synchronization issue between your machine and the server: https://github.com/hasura/graphql-engine/issues/1912

Some JWT validation libraries allow `time skew` setting to set the tolerated time difference between servers. 

If you're a Mac user, this might help: https://github.com/hasura/graphql-engine/issues/1912#issuecomment-1279849697

**Comment by seanaguinaga** [comment]
Got it, and thank you! I'd say it's resolved and refreshing properly when using the emulator regardless

What's funny is that I am running hasura in a docker container on my Mac with the firebase auth emulator so it's weird to think there would be a time issue on the same machine but there is somehow 😂

**Comment by awinogrodzki** [comment]
I can think of a test where you restart Hasura container and look for Errors. If there are no errors at the start of the process, but they start to occur after some time of VM being suspended, it could mean that the VM get's out of sync.

Supposably the error does not happen when using Docker without Docker Desktop, but I haven't tested that :-)

**Comment by awinogrodzki** [comment]
I am closing the issue.

Please let me know if you have some findings regarding the JWTIssuedAtFuture error. 

BTW. I see that you can configure Hasura in Docker to compensate for clock sync issues: https://github.com/supertokens/supertokens-core/issues/467 :-)
