### ISSUE TITLE
error - Too big integer

### ISSUE THREAD

**Issue by seanaguinaga** [ensite-in/next-firebase-auth-edge#15]
<img width="937" alt="Screenshot 2023-01-05 at 12 43 52 PM" src="https://user-images.githubusercontent.com/15254340/210877055-4c1a60da-b090-41f8-9b28-0b508c1c3696.png">

and

<img width="1725" alt="Screenshot 2023-01-05 at 12 42 56 PM" src="https://user-images.githubusercontent.com/15254340/210877082-e7d951a9-24fe-46ba-af71-660ac37da62a.png">

are what I am seeing with an unchanged emulator example repo

can send an example repo with my env

**Comment by seanaguinaga** [comment]
Tried again on a clean repo and another pc and cannot repro

Not sure what caused it now to be honest

Closing until it comes up again if ever

**Comment by vladgardus** [comment]
I'm getting the same error:
error - node_modules\next-firebase-auth-edge\lib\auth\jwt\crypto-signer.js (21:0) @ ServiceAccountSigner.sign
error - Too big integer

@seanaguinaga  Did you change something in the environment variables in the new repo?

**Comment by seanaguinaga** [comment]
Not that I could tell/am aware of, no

I figured it was a package issue

I kept getting an encoding package missing warning with 0.2.14 and earlier I believe and with 0.2.15 that went away

**Comment by awinogrodzki** [comment]
@seanaguinaga do you think this could be the reason: https://github.com/ensite-in/next-firebase-auth-edge/issues/17 ?

**Comment by seanaguinaga** [comment]
yeah that's the same issue!

0.2.15 and removing node_modules/yarn.lock fixed it for me though? but it could be something with that encoding library or even fetch related based on the messages I was receiving
