### ISSUE TITLE
Firebase Hosting only permits a single cookie

### ISSUE THREAD

**Issue by matthewlongpre** [ensite-in/next-firebase-auth-edge#19]
Hey there, thanks for a great library! I've been experimenting with it and it's working great for me locally. However, it's not working when I deploy to Firebase Hosting.

After a bit of digging, it turns out that [Firebase Hosting strips all cookies except for a cookie named `__session` specifically](https://firebase.google.com/docs/hosting/manage-cache#using_cookies). So if I pass in `cookieName: '__session'` to `createAuthMiddlewareResponse`, the `signedCookie` gets set correctly. However, the `signatureCookie` will not be set, and so auth doesn't work successfully (`getTokens` will return `null`).

I'm curious if you have any thoughts or advice? Cheers!

**Comment by awinogrodzki** [comment]
Hey @matthewlongpre! 

Good question. I haven't used Firebase Hosting myself, but I think I know what there're trying to achieve. The name `__session` suggests that instead of encrypting a JWT and storing it in a cookie, they want you to store the JWT in session (eg. express-session, or simple Redis storage) and set unique identifier for session in cookies. I imagine the flow as follows:

1. Unauthenticated user opens an app
2. App logs user via Firebase Authentication library
3. App registers `onIdTokenChanged` handler that detects change in credentials, sends user token to some api endpoint (eg. /api/login)
4. `/api/login` endpoint, upon receiving request, reads the token, passes it to Firebase in exchange for `idToken` and `refreshToken`, saves it in session and sets `Set-Cookie: __session=SESSION_ID` header in a response

On any subsequent request, your backend should extract the id and refresh tokens using provided SESSION_ID and thus authenticate the user based on a single cookie.

What would be needed here is Next.js Edge runtime compatible session solution. For testing purposes it can be a simple in-memory storage.

After you are able to extract id and refresh tokens from session, you could use `verifyAndRefreshExpiredIdToken` from this library to validate the user in Middleware or server components :-) 

If you find any lightweight and Edge-compatible session solution please let me know. I'll add some useful example.

Please let me know if this answers your question

**Comment by matthewlongpre** [comment]
Thanks for the suggestions! I've managed to get something working. For now at least, I'm storing the session details (`idToken`, `refreshToken`) in Firestore (using the client SDK - not `firebase-admin`).

I'm curious if you think Firestore is a reasonable option? I haven't experimented with Redis yet.

Here is my implementation in case it helps anyone else. 

```ts
// middleware.ts

const COOKIE_NAME = "__session"; // Firebase Hosting requires the cookie to be named `__session`
const API_LOGIN_PATH = "/api/login";
const API_LOGOUT_PATH = "/api/logout";
const PAGE_LOGIN_PATH = "/login";

export const commonOptions: CreateAuthMiddlewareOptions = {
  apiKey: firebaseConfig.apiKey,
  cookieName: COOKIE_NAME,
  cookieSerializeOptions: {
    path: "/",
    httpOnly: true,
    secure: true,
    sameSite: "strict" as const,
    maxAge: 12 * 60 * 60 * 24 * 1000, // twelve days
  },
  loginPath: API_LOGIN_PATH,
  logoutPath: API_LOGOUT_PATH,
  serviceAccount,
};

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico).*)",
  ],
};

export async function middleware(request: NextRequest) {
  if ([API_LOGIN_PATH, API_LOGOUT_PATH].includes(request.nextUrl.pathname)) {
    return createAuthMiddlewareResponse(request, commonOptions);
  }

  const tokens = await getTokens(request.cookies, commonOptions);
  const isVerified = Boolean(tokens?.decodedToken.email_verified);
  const isLoginPage = request.nextUrl.pathname === PAGE_LOGIN_PATH;

  const shouldRedirectToLogin = !isVerified && !isLoginPage;
  const shouldRedirectToHome = isVerified && isLoginPage;

  if (shouldRedirectToLogin) {
    const url = request.nextUrl.clone();
    url.pathname = PAGE_LOGIN_PATH;

    return NextResponse.redirect(url);
  }

  if (shouldRedirectToHome) {
    const url = request.nextUrl.clone();
    url.pathname = "/";

    return NextResponse.redirect(url);
  }
}

```

```ts
export interface CreateAuthMiddlewareOptions {
  apiKey: string;
  cookieName: string;
  cookieSerializeOptions: CookieSerializeOptions;
  loginPath: string;
  logoutPath: string;
  serviceAccount: ServiceAccount;
}

export async function createAuthMiddlewareResponse(
  request: NextRequest,
  options: CreateAuthMiddlewareOptions
) {
  if (request.nextUrl.pathname === options.loginPath) {
    return setSessionId(request, options);
  }

  if (request.nextUrl.pathname === options.logoutPath) {
    return removeSessionId(request, options);
  }
}
```

```ts
// cookies.ts

export interface SetSessionIdOptions {
  cookieName: string;
  cookieSerializeOptions: CookieSerializeOptions;
  serviceAccount: ServiceAccount;
  apiKey: string;
}

export async function setSessionId(
  request: NextRequest,
  options: SetSessionIdOptions
): Promise<NextResponse> {
  const { getCustomIdAndRefreshTokens } = getFirebaseAuth(
    options.serviceAccount,
    options.apiKey
  );

  const token = request.headers.get("Authorization")?.split(" ")[1] ?? "";

  const { idToken, refreshToken } = await getCustomIdAndRefreshTokens(
    token,
    options.apiKey
  );

  const response = new NextResponse(JSON.stringify({ success: true }), {
    status: 200,
    headers: { "content-type": "application/json" },
  });

  // Store session in Firestore via the Firebase client SDK (`firebase-admin` cannot run in Edge functions)
  const collectionRef = collection(databaseRef, "user_sessions");
  const sessionDoc = await addDoc(collectionRef, { idToken, refreshToken });

  response.headers.append(
    "Set-Cookie",
    serialize(options.cookieName, sessionDoc.id, options.cookieSerializeOptions)
  );

  return response;
}

export interface RemoveAuthCookiesOptions {
  cookieName: string;
  cookieSerializeOptions: CookieSerializeOptions;
}

export async function removeSessionId(
  request: NextRequest,
  options: RemoveAuthCookiesOptions
): Promise<NextResponse> {
  const cookie = request.cookies.get(options.cookieName);

  if (cookie) {
    const sessionDocRef = doc(databaseRef, "user_sessions", cookie.value);
    deleteDoc(sessionDocRef);
  }

  const response = new NextResponse(JSON.stringify({ success: true }), {
    status: 200,
    headers: { "content-type": "application/json" },
  });

  const { maxAge, expires, ...cookieOptions } = options.cookieSerializeOptions;

  response.headers.append(
    "Set-Cookie",
    serialize(options.cookieName, "", {
      ...cookieOptions,
      expires: new Date(0),
    })
  );

  return response;
}
```

```ts
// tokens.ts

export interface GetTokensOptions {
  cookieName: string;
  apiKey: string;
  serviceAccount: ServiceAccount;
}

export async function getTokens(
  cookies: RequestCookies | ReadonlyRequestCookies,
  options: GetTokensOptions
) {
  const { verifyAndRefreshExpiredIdToken } = getFirebaseAuth(
    options.serviceAccount,
    options.apiKey
  );

  const cookie = cookies.get(options.cookieName);
  if (!cookie) return null;

  const collectionRef = collection(databaseRef, "user_sessions");
  const docRef = doc(collectionRef, cookie.value);

  const sessionDoc = await getDoc(docRef);

  const { idToken, refreshToken } =
    (sessionDoc.data() as IdAndRefreshTokens) || {};

  return verifyAndRefreshExpiredIdToken(idToken, refreshToken);
}
```

**Comment by awinogrodzki** [comment]
@matthewlongpre thanks for the implementation. It looks just as I imagined it. There's a one caveat when it comes to storing session details in Firestore. You need to take into account that each user request would have to call Firestore before actually processing the user request. This would add additional overhead to a response time. I suggested Redis, because it serves value directly from memory. 

You could improve your solution by introducing some in-memory caching. Eg:

```typescript
const inMemoryCache = {};
async function getSessionTokens(sessionId: string) {
  if (inMemoryCache[sessionId]) {
     return inMemoryCache[sessionId];
  }
  
  const collectionRef = collection(databaseRef, "user_sessions");
  const docRef = doc(collectionRef, sessionId);

  const sessionDoc = await getDoc(docRef);
  
  return inMemoryCache[sessionId] = sessionDoc.data();
} 
```

But then you'd have to remember to update `inMemoryCache` each time `idToken` or `refreshToken` has changed. The least you could do is to clear this cache for given session id every 60 minutes – `idToken` is valid for 60 minutes after first login

**Comment by awinogrodzki** [comment]
I will close the issue. If you have any other questions or remarks please let me know under this thread :-)

**Comment by matthewlongpre** [comment]
Thanks, appreciate your insights!

**Comment by shawn1130** [comment]
> Thanks for the suggestions! I've managed to get something working. For now at least, I'm storing the session details (`idToken`, `refreshToken`) in Firestore (using the client SDK - not `firebase-admin`).
> 
> I'm curious if you think Firestore is a reasonable option? I haven't experimented with Redis yet.
> 
> Here is my implementation in case it helps anyone else.
> 
> ```ts
> // middleware.ts
> 
> const COOKIE_NAME = "__session"; // Firebase Hosting requires the cookie to be named `__session`
> const API_LOGIN_PATH = "/api/login";
> const API_LOGOUT_PATH = "/api/logout";
> const PAGE_LOGIN_PATH = "/login";
> 
> export const commonOptions: CreateAuthMiddlewareOptions = {
>   apiKey: firebaseConfig.apiKey,
>   cookieName: COOKIE_NAME,
>   cookieSerializeOptions: {
>     path: "/",
>     httpOnly: true,
>     secure: true,
>     sameSite: "strict" as const,
>     maxAge: 12 * 60 * 60 * 24 * 1000, // twelve days
>   },
>   loginPath: API_LOGIN_PATH,
>   logoutPath: API_LOGOUT_PATH,
>   serviceAccount,
> };
> 
> export const config = {
>   matcher: [
>     "/((?!_next/static|_next/image|favicon.ico).*)",
>   ],
> };
> 
> export async function middleware(request: NextRequest) {
>   if ([API_LOGIN_PATH, API_LOGOUT_PATH].includes(request.nextUrl.pathname)) {
>     return createAuthMiddlewareResponse(request, commonOptions);
>   }
> 
>   const tokens = await getTokens(request.cookies, commonOptions);
>   const isVerified = Boolean(tokens?.decodedToken.email_verified);
>   const isLoginPage = request.nextUrl.pathname === PAGE_LOGIN_PATH;
> 
>   const shouldRedirectToLogin = !isVerified && !isLoginPage;
>   const shouldRedirectToHome = isVerified && isLoginPage;
> 
>   if (shouldRedirectToLogin) {
>     const url = request.nextUrl.clone();
>     url.pathname = PAGE_LOGIN_PATH;
> 
>     return NextResponse.redirect(url);
>   }
> 
>   if (shouldRedirectToHome) {
>     const url = request.nextUrl.clone();
>     url.pathname = "/";
> 
>     return NextResponse.redirect(url);
>   }
> }
> ```
> 
> ```ts
> export interface CreateAuthMiddlewareOptions {
>   apiKey: string;
>   cookieName: string;
>   cookieSerializeOptions: CookieSerializeOptions;
>   loginPath: string;
>   logoutPath: string;
>   serviceAccount: ServiceAccount;
> }
> 
> export async function createAuthMiddlewareResponse(
>   request: NextRequest,
>   options: CreateAuthMiddlewareOptions
> ) {
>   if (request.nextUrl.pathname === options.loginPath) {
>     return setSessionId(request, options);
>   }
> 
>   if (request.nextUrl.pathname === options.logoutPath) {
>     return removeSessionId(request, options);
>   }
> }
> ```
> 
> ```ts
> // cookies.ts
> 
> export interface SetSessionIdOptions {
>   cookieName: string;
>   cookieSerializeOptions: CookieSerializeOptions;
>   serviceAccount: ServiceAccount;
>   apiKey: string;
> }
> 
> export async function setSessionId(
>   request: NextRequest,
>   options: SetSessionIdOptions
> ): Promise<NextResponse> {
>   const { getCustomIdAndRefreshTokens } = getFirebaseAuth(
>     options.serviceAccount,
>     options.apiKey
>   );
> 
>   const token = request.headers.get("Authorization")?.split(" ")[1] ?? "";
> 
>   const { idToken, refreshToken } = await getCustomIdAndRefreshTokens(
>     token,
>     options.apiKey
>   );
> 
>   const response = new NextResponse(JSON.stringify({ success: true }), {
>     status: 200,
>     headers: { "content-type": "application/json" },
>   });
> 
>   // Store session in Firestore via the Firebase client SDK (`firebase-admin` cannot run in Edge functions)
>   const collectionRef = collection(databaseRef, "user_sessions");
>   const sessionDoc = await addDoc(collectionRef, { idToken, refreshToken });
> 
>   response.headers.append(
>     "Set-Cookie",
>     serialize(options.cookieName, sessionDoc.id, options.cookieSerializeOptions)
>   );
> 
>   return response;
> }
> 
> export interface RemoveAuthCookiesOptions {
>   cookieName: string;
>   cookieSerializeOptions: CookieSerializeOptions;
> }
> 
> export async function removeSessionId(
>   request: NextRequest,
>   options: RemoveAuthCookiesOptions
> ): Promise<NextResponse> {
>   const cookie = request.cookies.get(options.cookieName);
> 
>   if (cookie) {
>     const sessionDocRef = doc(databaseRef, "user_sessions", cookie.value);
>     deleteDoc(sessionDocRef);
>   }
> 
>   const response = new NextResponse(JSON.stringify({ success: true }), {
>     status: 200,
>     headers: { "content-type": "application/json" },
>   });
> 
>   const { maxAge, expires, ...cookieOptions } = options.cookieSerializeOptions;
> 
>   response.headers.append(
>     "Set-Cookie",
>     serialize(options.cookieName, "", {
>       ...cookieOptions,
>       expires: new Date(0),
>     })
>   );
> 
>   return response;
> }
> ```
> 
> ```ts
> // tokens.ts
> 
> export interface GetTokensOptions {
>   cookieName: string;
>   apiKey: string;
>   serviceAccount: ServiceAccount;
> }
> 
> export async function getTokens(
>   cookies: RequestCookies | ReadonlyRequestCookies,
>   options: GetTokensOptions
> ) {
>   const { verifyAndRefreshExpiredIdToken } = getFirebaseAuth(
>     options.serviceAccount,
>     options.apiKey
>   );
> 
>   const cookie = cookies.get(options.cookieName);
>   if (!cookie) return null;
> 
>   const collectionRef = collection(databaseRef, "user_sessions");
>   const docRef = doc(collectionRef, cookie.value);
> 
>   const sessionDoc = await getDoc(docRef);
> 
>   const { idToken, refreshToken } =
>     (sessionDoc.data() as IdAndRefreshTokens) || {};
> 
>   return verifyAndRefreshExpiredIdToken(idToken, refreshToken);
> }
> ```

How did you get firebase client sdk to work in the middleware? I am getting the following error due to the firebase client sdk
`Error: The edge runtime does not support Node.js 'http2' module.`

**Comment by matthewlongpre** [comment]
> 

Hey @shawn1130 - it sounds like you might be using `[firebase-admin](https://firebase.google.com/docs/admin/setup/)` which uses Node.js modules. I was using the Firebase Client SDK which can run in the browser: https://www.npmjs.com/package/firebase
