### ISSUE TITLE
Getting occasional `TOKEN_EXPIRED` errors in the middlewere when refreshing expired token

### ISSUE THREAD

**Issue by steve-marmalade** [ensite-in/next-firebase-auth-edge#21]
I have started to occasionally see the following error message in our middleware logs:
```
Error: Error during refreshing expired token: {"error":{"code":400,"message":"TOKEN_EXPIRED","status":"INVALID_ARGUMENT"}}
    at (node_modules/next-firebase-auth-edge/lib/auth/index.js:69:0)
    at (node_modules/next-firebase-auth-edge/lib/auth/index.js:84:0)
```

1. Is there any context you can help provide on when this error would occur? Is it possible that a password reset could have revoked the token, and the cookie was not updated with a new one (which could happen if the reset occurred on a different browser/device)? My understanding is that the refresh tokens should never expire in Firebase Auth, so I was not expecting to need to handle this case.
2. I can catch the generic error in my application code, but if this is an expected event, then it might be nice for the library to wrap this similar to how you handled USER_NOT_FOUND in #9

**Comment by awinogrodzki** [comment]
Hey @steve-marmalade, thanks for the question. I should definitely improve error handling in this case and return FirebaseError instead of generic one. I'd also look into official lib to see if I can provide some more context on the error. Stay put!

**Comment by awinogrodzki** [comment]
@steve-marmalade,

In https://github.com/ensite-in/next-firebase-auth-edge/pull/22 I've handled refresh token error exactly as it's being done in the official lib, by re-throwing `auth/invalid-credential` error during the refresh. 

You can use it by installing `next-firebase-auth-edge@0.3.1`. Whenever error is thrown during token validation, you can use `isInvalidCredentialError` convenience method from `next-firebase-auth-edge/lib/auth` to redirect user to login screen.

I also log `error_description` that comes with the error response. Unfortunately in your case Google did not return any `error_description`. Maybe it's worth to setup additional logs around user actions to narrow down the use case and try to reproduce the issue?

**Comment by awinogrodzki** [comment]
I will close the issue, as it's now possible to handle invalid-credential error
