### ISSUE TITLE
Emulator Issues

### ISSUE THREAD

**Issue by seanaguinaga** [ensite-in/next-firebase-auth-edge#4]
Hey!

Have you been able to get the emulators to work on your end?

I get a JWT error because the emulator does not use signed tokens.

Tried to follow the src but can't figure out what to do.

Can I try to add an example for emulator and let you know when I get stuck?

**Comment by awinogrodzki** [comment]
Hey @seanaguinaga!

Thanks for reporting :-)

I've begun to implement Emulator support, but haven't tested that yet, so there's a good chance it's not working as expected. 

I'll be very grateful for emulator example, just to make sure we are on the same page.

**Comment by awinogrodzki** [comment]
@seanaguinaga please feel free to create a branch/PR with emulator example and we'll fix it there :-)

**Comment by awinogrodzki** [comment]
@seanaguinaga I've managed to create firebase emulator example and reproduce the issue.

Following PR should add support for Firebase Authentication Emulator:
https://github.com/ensite-in/next-firebase-auth-edge/pull/8

Could you take a look and see if it solves your issue?

**Comment by seanaguinaga** [comment]
This works perfectly! 

Readme and instructions are good too!


Always difficult to know where libraries should being or end but the auth-provider is pretty awesome and is getting semi-proprietary:
Would you want to have that be a part of the lib or leave it as is? (an example snippet/external component)

**Comment by awinogrodzki** [comment]
I plan to include auth provider in the lib, that's one of my near future tasks :-)

**Comment by awinogrodzki** [comment]
Fix released in [v0.2.14](https://github.com/ensite-in/next-firebase-auth-edge/blob/main/CHANGELOG.md#0214)
