### ISSUE TITLE
Bump node engine to current LTS

### ISSUE THREAD

**Issue by thomasftg** [ensite-in/next-firebase-auth-edge#5]
Currently the upper end of node does not include 18.12.x LTS

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next-firebase-auth-edge@0.2.9',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '>=16.0.0 <17.0.0',
npm WARN EBADENGINE     npm: '>=8.0.0 <9.0.0',
npm WARN EBADENGINE     yarn: '>=1.22.0 <2.0.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v18.12.0', npm: '8.19.2' }
npm WARN EBADENGINE }

**Comment by awinogrodzki** [comment]
Solved in `v0.2.10`

Fix by installing latest version of the library
